### ISSUE TITLE
Anyone wants to use latest version of android API 30+ 

### ISSUE THREAD

**Issue by amandylabs** [sampart/cordova-plugin-app-version#137]
Anyone wants to use latest version of android API 30+ 
use below version Cordova plugin.
This updated plugin goes to 

cordova plugin add cordova-plugin-get-app-version
https://www.npmjs.com/package/cordova-plugin-get-app-version

Soucre has Written by and credited to [Robert (Jamie) Munro](http://twitter.com/rjmunro) at [White October](http://whiteoctober.co.uk/)

**Comment by sampart** [comment]
Great to see you're offering to keep this work alive, @amandylabs, thank you!

It seems a shame that you're not referencing this original at all, though. Doing so could help others understand the project better, and would ensure that folk who worked on this code still get credit for it.

Why did you decide to copy/paste rather than fork?

**Comment by amandylabs** [comment]
There were a lot of deprecated versions of plugins. Many developers are facing problems due to the latest update of Cordova and Android SDK. We understand that you are unable to update this plugin due to your reason. Just trying to help others.

**Comment by sampart** [comment]
I do appreciate your help. Thanks for adding https://github.com/amandylabs/cordova-plugin-get-app-version/commit/ab3b99edc78484b3da438fd5cfb09c39e048171f now.
